---

version: '3'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/app42
      SPRING_DATASOURCE_USERNAME: userdb
      SPRING_DATASOURCE_PASSWORD: password123

  mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: app42
      MYSQL_USER: userdb
      MYSQL_PASSWORD: password123
    volumes:
      - app42:/var/lib/mysql
volumes:
  app42: