version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app42paas
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password