---

version: '3'
services:
  app:
    build:
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.116.174.97:3306/
      SPRING_DATASOURCE_USERNAME: userdb
      SPRING_DATASOURCE_PASSWORD: password
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: APP42
      MYSQL_USER: userdb
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password