---
version: '3'
services:
   package-maven:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - db
   db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'APP42'
        MYSQL_USER: userdb
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
      ports:
        - "3306:3306"
      expose:
        - '3306'
      volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db