---

version: '3'
services:
  app:
    build:
        context: /usr/app/App42
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/APP42
      SPRING_DATASOURCE_USERNAME: userdb
      SPRING_DATASOURCE_PASSWORD: password
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: APP42
      MYSQL_USER: userdb
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password