version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app42paas-java-mysql-sample:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.118.87.20:3306/APP42
      SPRING_DATASOURCE_USERNAME: userdb
      SPRING_DATASOURCE_PASSWORD: password

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: passwordroot
      MYSQL_DATABASE: APP42
      MYSQL_USER: userdb
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"